matrix:
  include:
    - language: python
      dist: xenial
      python: 3.7
      script: py.test

    - language: node_js
      node_js: 11
      dist: xenial
      before_script:
        - cd js
        - npm install
